# Generated by Django 3.0.6 on 2021-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('atitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('due', models.CharField(blank=True, max_length=1000, null=True)),
                ('drop', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignment', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignment', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('notiURL', models.CharField(blank=True, max_length=1000, null=True)),
                ('resoURL', models.CharField(blank=True, max_length=1000, null=True)),
                ('assiURL', models.CharField(blank=True, max_length=1000, null=True)),
                ('zoomURL', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
